version: '3.8'

services:
  airportcontrol-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5051:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - CacheOptions__BaseUrl=redis:6379
    restart: unless-stopped
    depends_on:
      - redis

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    restart: unless-stopped
